### ISSUE TITLE
How do I use the gui?

### ISSUE THREAD

**Issue by Evilpersonwithnosoul** [HyperGabe/Discord-Data-Package-Parser#1]
which data package? Because I only got the .exe

**Comment by HyperGabe** [comment]
The data package is something that can be requested from discord (https://support.discordapp.com/hc/en-us/articles/360004027692-Requesting-a-Copy-of-your-Data) which should send a zip file containing all of your data. You will need to request this data first to be able to use the GUI

**Comment by Evilpersonwithnosoul** [comment]
Thanks.
