### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by wick78** [HyperGabe/Discord-Data-Package-Parser#3]
hi im sorry but im having trouble figuring out how to execute this application and get it to open. im new but know how much easier this application will make viewing direct messages in my data package and seeing who they are from and help would be greatly appreciated.

**Comment by HyperGabe** [comment]
Could I ask for more information on what is happening when you try to open it? Are you getting any error messages when trying to execute the program?

**Comment by wick78** [comment]
i dont even know which file im suppose to click to execute it

**Comment by wick78** [comment]
i literally have no idea how to launch this program at all

**Comment by HyperGabe** [comment]
Are you downloading only the source code? I have an executable that's already built you can download here https://github.com/HyperGabe/Discord-Data-Package-Parser/releases

**Comment by wick78** [comment]
thank you so much

**Comment by wick78** [comment]
and this will show every single person i ever sent a direct message to in
the data package ?

**Comment by HyperGabe** [comment]
It will show every message that you have sent, as long as it has not been deleted.
