### ISSUE TITLE
Blank conversations

### ISSUE THREAD

**Issue by wick78** [HyperGabe/Discord-Data-Package-Parser#4]
there are some dm conversations that have nothing in them. so im confused because i thought discord said if you deleted direct messages they are gone and will not show up in the data package.

**Comment by HyperGabe** [comment]
heya I'm sorry for not responding earlier, I only just saw this message. Could you give a more detailed example of what you mean?

**Comment by wick78** [comment]
Like the dm shows up but there are no messages inside of it. Does that mean
it was deleted ?

**Comment by HyperGabe** [comment]
by delete direct messages do you mean closing them in the app? also if a DM is blank it could mean that you have not sent them a message (or have deleted the messages)

**Comment by wick78** [comment]
You answered my question, that’s what I meant if the dm is blank. I
appreciate it very much.
