### ISSUE TITLE
No messages loading

### ISSUE THREAD

**Issue by OJVAL** [HyperGabe/Discord-Data-Package-Parser#5]
Hi - when I select the data package folder on the UI, nothing actually opens. Do you know why this might be?

**Comment by HyperGabe** [comment]
hello, just to be sure. Are you making sure that the selected directory is being chosen? and also make sure there isn't another data package folder in your folder

**Comment by OJVAL** [comment]
Thank you for the swift reply! :) I'm not entirely sure what the issue was, but I extracted the file to a different folder and it worked great. This is really helpful - thank you and sorry for being dense lol

**Comment by HyperGabe** [comment]
It's no problem, I'm glad your issue is resolved though :3. it did seem to be an error on the folder you selected and I'll need add more obvious error messages
